### ISSUE TITLE
Using this can we replace Blazorise with MudBlazor?

### ISSUE THREAD

**Issue by mhkhub** [yellow-dragon-cloud/AbpMudBlazorFinal#1]

**Comment by mhkhub** [comment]
1) Using this can we replace Blazorise with MudBlazor? 
2) how different is this from your new article (https://community.abp.io/posts/customize-abp-blazor-application-ui-with-mudblazor-wscmpu3w)

**Comment by yellow-dragon-cloud** [comment]
> 1. Using this can we replace Blazorise with MudBlazor?

Most of the UI is created with MudBlazor, instead of Blazorise.
Tenant management and settings pages are not covert in this sample. After customizing them as well, Blazorise can be deleted.

> 2. how different is this from your new article (https://community.abp.io/posts/customize-abp-blazor-application-ui-with-mudblazor-wscmpu3w)

No significant difference. But I sometimes fix and polish this repository, so this repo is more up to date with small changes.
